version: '3'
services:
    frontend:
        build:
            context: ./
        environment:
            - PORT=3000
            - NODE_ENV=production
        ports:
            - 3000:3000
        volumes:
            - ./:/var/www/html/nextjs
        depends_on: 
            - nodejs
        command: npm run dev

    nodejs:
        image: mhart/alpine-node:8
        container_name: node_js

